kind: Service
apiVersion: v1
metadata:
  name: app_load_bal_svc
spec: 
  type: LoadBalancer  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    clusterIP: 172.31.47.255
    loadBalancerIP: 192.168.252.128
  
 selector: 
   app: nginx

