apiVersion: v1
kind: Namespace
metadata:
  name: shared-volume
spec:

  volumes:
  -name: shared-dat
   emptyDir: {}
  
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
     
